### ISSUE TITLE
IPAddr::InvalidAddressError: invalid address with "rake eshop:retrieve_all"

### ISSUE THREAD

**Issue by icehaku** [Calyhre/eshop-prices#1]
Do you have time to help?
```

$ rake eshop:retrieve_all
rake aborted!
IPAddr::InvalidAddressError: invalid address
/home/dpge/.rvm/gems/ruby-2.4.1/gems/httparty-0.15.2/lib/httparty/request.rb:142:in `perform'
/home/dpge/.rvm/gems/ruby-2.4.1/gems/httparty-0.15.2/lib/httparty.rb:563:in `perform_request'
/home/dpge/.rvm/gems/ruby-2.4.1/gems/httparty-0.15.2/lib/httparty.rb:489:in `get'
/home/dpge/projects/ruby/pessoal/myeshop/lib/eshop/prices.rb:17:in `block in list'
/home/dpge/projects/ruby/pessoal/myeshop/lib/eshop/prices.rb:14:in `each'
/home/dpge/projects/ruby/pessoal/myeshop/lib/eshop/prices.rb:14:in `flat_map'
/home/dpge/projects/ruby/pessoal/myeshop/lib/eshop/prices.rb:14:in `list'
/home/dpge/projects/ruby/pessoal/myeshop/lib/eshop/games/asia.rb:27:in `guess_new_ids'
/home/dpge/projects/ruby/pessoal/myeshop/lib/eshop/games/asia.rb:15:in `list'
/home/dpge/projects/ruby/pessoal/myeshop/lib/eshop/games.rb:9:in `list'
/home/dpge/projects/ruby/pessoal/myeshop/lib/tasks/eshop.rake:6:in `block (2 levels) in <top (required)>'
/home/dpge/.rvm/gems/ruby-2.4.1/gems/bugsnag-5.3.2/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
/home/dpge/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => eshop:retrieve_all => eshop:retrieve_games
(See full trace by running task with --trace)

```

**Comment by icehaku** [comment]
Sorry, it was a proxy problem. LOL
